# Server settings (ServerProperties)
server:
  port: 9011

# Spring specifics 

spring:
  application:
    name: admin-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emsv2?createDatabaseIfNotExist=true
    username: sa
    password: Welcome1
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      
# Eureka specifics 

eureka:
  instance:
    hostname: localhost
    metadata-map:
      cluster: admin-service
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/