# Spring specifics 

spring:
  application:
    name: rule-engine-service
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.163.com
    port: 25
    username: ostenant@163.com
    password: ostenant163
    properties:
      smtp: 
        auth: true
        starttls:  
          enable: true
          required: true
        socketFactory: 
          class: javax.net.ssl.SSLSocketFactory
    scheduler: 
      enabled: true
      priorityLevels: 5
      persistence: 
        enabled: true
        redis: 
          enabled: true
          embedded: true
          host: localhost
          port: 6381
          settings: appendfilename email_appendonly.aof, dir C:/Workspace/RedisCache
        desiredBatchSize: 40
        minKeptInMemory: 20
        maxKeptInMemory: 50

# Eureka specifics 

eureka:
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${vcap.services.ems-v2-eureka-service.credentials.uri}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]}
    metadataMap:
      instanceId: ${vcap.application.instance_id}
    metadata-map:
      cluster: rule-engine-service
    status-page-url: https://${vcap.application.uris[0]}${management.context-path:}/health
    non-secure-port-enabled: false
    secure-port-enabled: true

# Ribbon specifics 

ribbon:
  eureka:
   enabled: true

