# Server settings (ServerProperties)
server:
  port: 9014

# Spring specifics 

spring:
  application:
    name: rule-engine-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  mail: # Email
    host: smtp.163.com
    port: 25
    username: ostenant@163.com
    password: ostenant163
    properties: 
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
            required: true
          socketFactory: 
            class: javax.net.ssl.SSLSocketFactory
    scheduler:
      enabled: true
      priorityLevels: 5
      persistence:
        enabled: true
        redis: 
          enabled: true
          embedded: true
          host: localhost
          port: 6381
          settings: appendfilename email_appendonly.aof, dir C:/Workspace/RedisCache
        desiredBatchSize: 40
        minKeptInMemory: 20
        maxKeptInMemory: 50
      
# Eureka specifics 

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# Ribbon specifics 

ribbon:
  eureka:
   enabled: true
   

# Local Proxy
local: 
  proxy:
    https:
      host: proxy.wdf.sap.corp
      port: 8080
    http: 
      host: proxy.wdf.sap.corp
      port: 8080
  