@startuml
left to right direction
skinparam packageStyle rectangle
'actor EMS系统管理员
'actor 实施顾问
'actor ERP系统管理员
'actor 销售人员

rectangle 第三方ERP系统 {

    :ERP系统管理员: --> (文档管理)
    :ERP系统管理员: --> (登录认证)
    :ERP系统管理员: --> (用户管理)
    :ERP系统管理员: --> (权限管理)
    :ERP系统管理员: --> (客户管理)
    :ERP系统管理员: --> (财务管理)
    :ERP系统管理员: --> (进销存管理)

    (文档管理) .> (合同管理) : generalize
    (文档管理) ..> (订单管理) : generalize


    (我的文档管理) <. (文档管理) : include
    :销售人员: --> (我的文档管理)
    (我的客户管理) <. (客户管理) : include
    :销售人员: --> (我的客户管理)
    :销售人员: --> (登录认证)
    :销售人员: --> (我的销售记录)

    (合同管理) ..> (修改合同) : include
    (合同管理) ..> (删除合同) : include
    (合同管理) ..> (扫描合同) : include
    (扫描合同) ..> (生成合同) : extends
    (合同管理) ..> (生成合同) : include
    (合同管理) ..> (查看合同) : include
    (合同管理) ..> (导入合同) : include
    (导入合同) ..> (批量导入合同) : extends
    (合同管理) ..> (导出合同) : include
    (导出合同) ..> (批量导出合同) : extends
    (查看合同) -> (查看合同列表)
    (查看合同列表) --> (查看合同详情)

    (订单管理) ..> (修改订单) : include
    (订单管理) ..> (删除订单) : include
    (订单管理) ..> (生成订单) : include
    (订单管理) ..> (查看订单) : include
    (订单管理) ..> (导入订单) : include
    (导入订单) ..> (批量导入订单) : extends
    (订单管理) ..> (导出订单) : include
    (导出订单) ..> (批量导出订单) : extends
    (查看订单) --> (查看订单列表)
    (查看订单列表) --> (查看订单详情)
}





@enduml